sonar.projectKey=ntms-wapp
sonar.projectName=ntms-wapp
sonar.qualitygate.wait=false
sonar.language=js
sonar.sources=.
sonar.exclusions =**/node_modules/**,**/src/assets/**,**/build/**,**/public/**,**/__tests__/**,**__mocks__**,**/screen/newDetailPage/*, **/screen/detailspages/*, **/src/screen/topWidgetDetails/*, **/src/screen/users/*, **/src/screen/user-profile/*, **/src/screen/newManagePricing/*, **/src/screen/manageAsset/charger/charger-model/*, **/src/formGenerator/asset/* , **/src/screen/alert/*, **/test/saga.js, **/AssociatedChargersTable2.js, **/Diagnostics.js, **/service/**, **/reports-inner/Report-Users.js, **/googleMap/**, **/map/**, **/config/**,**/src/reportWebVitals.js,/**jest.config.js,
sonar.sourceEncoding=UTF-8
